class String
  scrabblescores = Hash.new()
  scrabblescores.store("A", 1)
  scrabblescores.store("a", 1)
  scrabblescores.store("E", 1)
  scrabblescores.store("e", 1)
  scrabblescores.store("I", 1)
  scrabblescores.store("i", 1)
  scrabblescores.store("O", 1)
  scrabblescores.store("o", 1)
  scrabblescores.store("U", 1)
  scrabblescores.store("u", 1)
  scrabblescores.store("L", 1)
  scrabblescores.store("l", 1)
  scrabblescores.store("N", 1)
  scrabblescores.store("n", 1)
  scrabblescores.store("R", 1)
  scrabblescores.store("r", 1)
  scrabblescores.store("S", 1)
  scrabblescores.store("s", 1)
  scrabblescores.store("T", 1)
  scrabblescores.store("t", 1)
  scrabblescores.store("D", 2)
  scrabblescores.store("d", 2)
  scrabblescores.store("G", 2)
  scrabblescores.store("g", 2)
  scrabblescores.store("B", 3)
  scrabblescores.store("b", 3)
  scrabblescores.store("C", 3)
  scrabblescores.store("c", 3)
  scrabblescores.store("M", 3)
  scrabblescores.store("m", 3)
  scrabblescores.store("P", 3)
  scrabblescores.store("p", 3)
  scrabblescores.store("F", 4)
  scrabblescores.store("f", 4)
  scrabblescores.store("H", 4)
  scrabblescores.store("h", 4)
  scrabblescores.store("V", 4)
  scrabblescores.store("v", 4)
  scrabblescores.store("W", 4)
  scrabblescores.store("w", 4)
  scrabblescores.store("Y", 4)
  scrabblescores.store("y", 4)
  scrabblescores.store("K", 5)
  scrabblescores.store("k", 5)
  scrabblescores.store("J", 8)
  scrabblescores.store("j", 8)
  scrabblescores.store("X", 8)
  scrabblescores.store("x", 8)
  scrabblescores.store("Q", 10)
  scrabblescores.store("q", 10)
  scrabblescores.store("Z", 10)
  scrabblescores.store("z", 10)
  define_method(:scrabble) do
    score = 0
    input_letters = self.split("")
    input_letters.each() do |input_letter|
      score = score + scrabblescores.fetch(input_letter)
    end
    score
  end

end
